# Generated by Django 5.0.6 on 2025-03-01 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('target_url', models.URLField(max_length=256, verbose_name='目标URL')),
                ('ipaddr', models.CharField(max_length=128, verbose_name='IP地址')),
                ('scan_type', models.CharField(choices=[('active', '主动扫描'), ('passive', '被动扫描'), ('mixed', '混合扫描')], default='active', max_length=10, verbose_name='扫描类型')),
                ('scan_status', models.CharField(choices=[('pending', '等待扫描'), ('running', '扫描中'), ('completed', '已完成'), ('failed', '扫描失败')], default='pending', max_length=10, verbose_name='扫描状态')),
                ('risk_level', models.CharField(choices=[('high', '高危'), ('medium', '中危'), ('low', '低危'), ('info', '信息')], default='info', max_length=10, verbose_name='风险等级')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'burp',
            },
        ),
        migrations.CreateModel(
            name='BurpResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.CharField(max_length=128, verbose_name='目标IP地址')),
                ('port', models.CharField(max_length=128, verbose_name='端口')),
                ('vuln_type', models.CharField(choices=[('sqli', 'SQL注入'), ('xss', 'XSS跨站'), ('rce', '远程命令执行'), ('file_upload', '文件上传'), ('info_leak', '信息泄露'), ('other', '其他')], default='other', max_length=20, verbose_name='漏洞类型')),
                ('vuln_description', models.TextField(blank=True, verbose_name='漏洞描述')),
                ('poc', models.TextField(blank=True, verbose_name='验证POC')),
                ('account', models.CharField(blank=True, max_length=128, verbose_name='账号')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='密码')),
                ('fix_suggestion', models.TextField(blank=True, verbose_name='修复建议')),
                ('verify_status', models.CharField(choices=[('unverified', '未验证'), ('verified', '已验证'), ('false_positive', '误报')], default='unverified', max_length=15, verbose_name='验证状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('burp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burp.burp', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': 'burp_result',
            },
        ),
    ]
