# Generated by Django 5.0.6 on 2025-03-01 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='站点名称')),
                ('ipaddr', models.CharField(max_length=128, verbose_name='目标IP地址')),
                ('record_type', models.CharField(choices=[('A', 'A记录'), ('AAAA', 'AAAA记录'), ('CNAME', 'CNAME记录'), ('MX', 'MX记录'), ('TXT', 'TXT记录'), ('NS', 'NS记录'), ('PTR', 'PTR记录'), ('SRV', 'SRV记录')], default='A', max_length=10, verbose_name='记录类型')),
                ('ttl', models.IntegerField(default=3600, verbose_name='TTL值')),
                ('dns_server', models.CharField(blank=True, max_length=128, verbose_name='DNS服务器')),
                ('priority', models.IntegerField(default=10, verbose_name='优先级')),
                ('status', models.IntegerField(choices=[(1, '可用'), (0, '不可用')], default=1, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='记录时间')),
                ('updated_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'dns',
                'verbose_name_plural': 'dns',
                'ordering': ['priority', '-created_time'],
            },
        ),
    ]
